### ISSUE TITLE
OWASP #10 - Unprotected Redirects

### ISSUE THREAD

**Issue by cmalekpour** [nVisium/django.nV#19]
For Grails.nV, I used an optional redirect to take you back to the last page after login. That would be pretty straightforward to implement and is also something easy to overlook on production websites

**Comment by sethlaw** [comment]
2e774f2 - Implemented redirect parameter on the logout functionality. Does not require a user to be authenticated to use.

**Comment by sethlaw** [comment]
Completed in last tutorial push.
