### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by cmalekpour** [nVisium/django.nV#27]
Clean up some inconsistencies in the code. At first glance:
* Columns in model have inconsistent naming
* Functions in code don't follow single naming pattern
* Organize code better
* Add more comments

**Comment by cmalekpour** [comment]
Columns and functions should now have consistent names as of 6d40a5d01e749cdf7485cd84c482bc00b816e844

**Comment by sethlaw** [comment]
Further code cleanup of views.py function names in d82af69.
