### ISSUE TITLE
Add explicit insecurity/vulnerability warnings at the top of each file

### ISSUE THREAD

**Issue by pydanny** [nVisium/django.nV#42]
While I don't know if demonstrating how to make a hackable Django site is a good or bad thing, I do know that the only place in the codebase where I'm explicitly told this is purposefully insecure is at the top of the README. While the other files may have 'insecure' spelled out in comments, there is no disclaimer at the top of each file.

From personal experience, if you post examples of bad code that shouldn't be used, it needs to be abundantly clear that this is the case. Otherwise people will find this code through searches, and implement it.

Please, please, please add an explicit warning at the top of each file.

**Comment by cmalekpour** [comment]
Great point, thanks! I'll go ahead and add a disclaimer to all files with code, and to pages in the app itself

**Comment by luzfcb** [comment]
@cmalekpour It would be nice to add the same warning for versions in other languages

**Comment by cmalekpour** [comment]
@luzfcb yep, actually doing i18n in general is a feature we should have
