### ISSUE TITLE
Feature Request: Time-based reset tokens

### ISSUE THREAD

**Issue by forced-request** [nVisium/django.nV#45]
Hi All,

I would like to see a password reset mechanism that generates a SecureRandom 6 digit token, and sends that via out-of-band communication (email). This token will be used to verify a users identity before allowing them to change the password. This token should last for 10 minutes before expiring.

The idea is that we can use this to train developers on the idea of distributed attacks. For example, even though the token is distributed out of band, it still lacks the required keyspace to make it considered cryptographically random. We can leverage this to enumerate the entire keyspace of the token, to reset a victims password.

**Comment by cmalekpour** [comment]
@forced-request at long last
