### ISSUE TITLE
Tutorial Formatting

### ISSUE THREAD

**Issue by forced-request** [nVisium/django.nV#47]
Here are a few issues I noticed with the tutorials.

**SQLi**: Solution only seems to cover secure file creation. It does not provide mitigation techniques for SQLi.

**IDOR**: doesn't leverage syntax highlighting for the code snippets.

**Components**: Lacks linebreaks and formatting.

**CSRF**: Lacks formatting

**Comment by cmalekpour** [comment]
7875075f2eb4ec35ea1fcb9dd84a1bbe15f069f7 should address this issue
