### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by webkodex** [nVisium/django.nV#74]
Hi am trying to install on Debian Jessie Vm but am met with errors, i have python 3.4+ installed on system,i cannot pip install -r requirements.txt as its asking for a directory, in which directory it should be installed ?& from where to start ./reset_db.sh ? kindly suggest
Regards
skorpinok
![screenshot from 2017-05-07 00-33-09](https://cloud.githubusercontent.com/assets/15958581/25777937/05dc31dc-32bd-11e7-841d-f5f7beffd86a.png)
.

**Comment by nVisium-seth-law** [comment]
Hey @webkodex:

Make sure you have downloaded the code from GitHub first, either via Zip or:

- git clone https://github.com/nvisium/django.nV.git

The CD into that directory and run the above commands.

--Seth

**Comment by webkodex** [comment]
Hi @nVisium-seth-law 

I git cloned django to a directory & installation went fine, but upon firing http://192.168.56.101:8000/ the browser says unable to connect. django is git cloned into cd /usr/share/nginx/html. i also tried other directory but nothing worked.  kindly suggest how to fix.

Regards
skorpinok

**Comment by webkodex** [comment]
@nVisium-seth-law 
screenshots

![capture1](https://cloud.githubusercontent.com/assets/15958581/25811858/2eac47b6-3432-11e7-8e43-31be77a38155.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15958581/25811857/2eaabb26-3432-11e7-9df9-6c74400771a7.PNG)

**Comment by nVisium-seth-law** [comment]
That is correct. By default, the server only comes up on localhost (127.0.0.1), if you want to access it over another port, startup the application by running:

- python3 manage.py runserver 192.168.56.101:8000

**Comment by webkodex** [comment]
@nVisium-seth-law 
Hi,  i navigate to that directory & run python3 manage.py runserver 192.168.56.101:8000, what i get is this error that No module named 'django'. i don't know where am exactly wrong, i did all installation as it was in " read me ". should i do a clean install ? or is there a way to fix it ? appreciating your support & cooperation thanks..

Regards
skorpinok
![capture3](https://cloud.githubusercontent.com/assets/15958581/25835389/eebce240-349b-11e7-8310-c8ca6e9fe6a5.PNG)
![dj](https://cloud.githubusercontent.com/assets/15958581/25835387/eeb59e54-349b-11e7-9d58-f788d0e9c1dc.PNG)
![p](https://cloud.githubusercontent.com/assets/15958581/25835388/eeb986fe-349b-11e7-9ddd-f425f5b20f53.PNG)

**Comment by nVisium-seth-law** [comment]
Oh, whoops, looks like django is installed under python2.7, use the following command instead:

- python manage.py runserver 192.168.56.101:8000

Alternatively, do a `pip3 install -r requirements` to get things wired up in python3

**Comment by webkodex** [comment]
@nVisium-seth-law 

Hi, its now fixed.everything is up & running. Thanks...

![dj](https://cloud.githubusercontent.com/assets/15958581/25879654/78158966-3550-11e7-93b7-1115facda93b.PNG)

**Comment by nVisium-seth-law** [comment]
Good call.
